apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-metrics
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-metrics
  template:
    metadata:
      labels:
        app: k8s-metrics
    spec:
      serviceAccountName: k8s-metrics
      containers:
        - name: k8s-metrics
          image: brijendrasingh0369/tmp-metrics-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: METRICS_PORT
              value: "8000"
            - name: SCRAPE_INTERVAL
              value: "30"
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 512mi
              cpu: 400m
