apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 0-rbac.yaml
  - 1-deployment.yaml
  - 2-service.yaml
images:
  - name: brijendrasingh0369/tmp-metrics-app
    newTag: sha-c875477
