apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
        - name: py-app
          image: brijendrasingh0369/tmp-python-app
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 512mi
              cpu: 400m
