apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 0-deployment.yaml
  - 1-service.yaml
images:
  - name: brijendrasingh0369/tmp-python-app
    newTag: bf577b1b6714299417f7f1180b74652fe4fe9bb3
