apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-app
  namespace: argocd
  argocd-image-updater.argoproj.io/image-list: my-app=brijendrasingh0369/tmp-metrics-app
  argocd-image-updater.argoproj.io/my-app.update-strategy: latest
  argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/brijendra-beehyv/contineous-delivery.git
    path: services/metrics-app
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
